### ISSUE TITLE
Release v5.17.0

### ISSUE THREAD

**Issue by PeterDaveHello** [transmission-remote-gui/NugetPackage#4]
I have no permission on https://chocolatey.org/packages/transgui yet.

I bumped the version here already:
https://github.com/transmission-remote-gui/NugetPackage/commit/45adce60457b18d39752b67aca984ad7ff573977

@mom1 please help publish new version, thanks!

**Comment by mom1** [comment]
Do you have account in chocolatey?

**Comment by PeterDaveHello** [comment]
Yes, same as GitHub ;)

**Comment by mom1** [comment]
check please. i add you in Maintainers

**Comment by PeterDaveHello** [comment]
@mom1 accepted! Nice, can you still help us publish v5.17.0 this time? Thanks.

**Comment by mom1** [comment]
ok. This take time because i not have windows.

**Comment by PeterDaveHello** [comment]
Oops, didn't know that, take your time please, I also work on non-windows environment (Ubuntu Linux)

**Comment by PeterDaveHello** [comment]
BTW, I'm not very familiar with chocolatey/nuget yet, it'll be great if we can have some doc to be followed, what do you think?

**Comment by PeterDaveHello** [comment]
I just uploaded v5.17.0 now waiting for approval

**Comment by PeterDaveHello** [comment]
Approved :tada:

**Comment by mom1** [comment]
Perfect :+1:
