### ISSUE TITLE
Enable Automatic Packaging

### ISSUE THREAD

**Issue by PeterDaveHello** [transmission-remote-gui/NugetPackage#5]
https://chocolatey.org/docs/automatic-packages

**Comment by PeterDaveHello** [comment]
Looks like it's done here: https://github.com/transmission-remote-gui/NugetPackage/blob/master/transgui/update.ps1, I'll use this one next time.

**Comment by mom1** [comment]
be careful, I had trable with unnecessary files in the resulting archive.

**Comment by PeterDaveHello** [comment]
@mom1 Okay, thanks, let's see if we could improve it
